apiVersion: v1
kind: Service
metadata:
  name: ems-backend   # 👈 alias for nginx
spec:
  selector:
    app: ems-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

